Repository GAZACODER/clients_data, pull requests merged in 2020-09, with the labels that each got.

#3 upload flie sturture folowing mvc #1
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/components/.gitkeep
  src/index.css
  src/index.js
  src/pages/.gitkeep
  src/utils/.gitkeep
Labels: MVC, request review

#4 Text Input [Component]
  src/components/.gitkeep
  src/components/TextInput/index.jsx
  src/components/TextInput/style.css
Labels: react component, request review

#7 Form Layout [Page]
  src/App.css
  src/App.js
  src/components/TextInput/style.css
Labels: inprogress, request review

#11 Logic local storage function
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: request review

#12 add table component #6
  src/components/Table/index.jsx
  src/components/Table/style.css
Labels: request review
